services:
  - type: web
    name: zkplosers-cl
    runtime: node
    buildCommand: npm install && npm run build && cd server && npm install && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: VITE_WS_URL
        value: wss://zkplosers-cl.onrender.com
    plan: free
